services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Infrastructure\Action\Action:
            public: true
            tags: ['controller.service_arguments']

    # ALIASES
    Domain\Model\Article\ArticleRepositoryInterface: '@article_repository_inmemory'

    # FORMS
    Infrastructure\Form\Type\CreateArticleFormType: ~

    # ACTIONS
    Infrastructure\Action\Article\CreateArticleAction: ~
    Infrastructure\Action\Article\ListArticleAction: ~

    # COMMAND HANDLERS
    Application\CommandHandler\CreateArticleCommandHandler:
        public: true
        tags:
            - { name: command_handler, handles: Application\Command\CreateArticleCommand }

    # QUERIES
    Application\Query\ListArticleQuery: ~

    # REPOSITORIES
    article_repository_doctrine:
        class: Infrastructure\Repository\Doctrine\ArticleRepository
        arguments: ['Domain\Model\Article\Article']
        factory: ['@doctrine.orm.entity_manager', getRepository]

    article_repository_inmemory:
      class: Infrastructure\Repository\InMemory\ArticleRepository


